$ANSIBLE_VAULT;1.1;AES256
36636561376366336532653735316135333231633666353733376436306263383561383332353233
3064623133383437346662336565366533613730386436350a353137373463363465386562613638
34363865356333366639663833366662376665396537646134383962303464313763353031656537
3136333166613537340a306638303863366530383032333961323164343732323039666536343265
64336136363762623264373538323666663139336132333562643764383532623966376661666662
31343836333764626266326333336239376436643537633661663138373963343333616538373136
396638666265646462363334613065633839
