---
- name: Ensure Python 3 is installed
  hosts: xcphosts
  gather_facts: false # skip because it requires Python
  become: true
  vars:
    # "yum search python3" shows python36
    # is available on XCP-ng version 8.2.
    python3_version: 3.6
    python3_package: python{{ python3_version | replace('.','') }}
    python3_path: /usr/bin/{{ python3_package }}
  pre_tasks:
    - name: Is Python 3 already installed?
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/raw_module.html
      ansible.builtin.raw: "{{ python3_path }} --version"
      register: check_result
      ignore_errors: true
      changed_when: false
  tasks:
    - name: Install YUM package "{{ python3_package }}"
      ansible.builtin.raw: yum install -y {{ python3_package }}
      when: check_result.rc
      changed_when: true

    - name: Link python3 to {{ python3_path }}
      ansible.builtin.raw: |
        update-alternatives --install /usr/bin/python3 python3 {{ python3_path }} 1
      when: check_result.rc
      changed_when: true
